### ISSUE TITLE
Nuget包可以更新啦 :happy

### ISSUE THREAD

**Issue by lightyears1998** [MonreeStudio/MonreeDate-Update#1]
下面这两只Reference可以退休了：

```xml
  <ItemGroup>
    <SDKReference Include="Microsoft.VCLibs.Desktop, Version=14.0">
      <Name>Visual C++ 2015 UWP Desktop Runtime for native apps</Name>
    </SDKReference>
    <SDKReference Include="SQLite.UWP.2015, Version=3.29.0">
      <Name>SQLite for Universal Windows Platform %28SQLite.UWP.2015, Version=3.29.0%29</Name>
    </SDKReference>
  </ItemGroup>
```

Nuget包管理器里头出了个`sqlite`包，功能跟`<SDKReference Include="SQLite.UWP.2015, Version=3.29.0">`是一样的。

**Comment by MonreeStudio** [comment]
呀，才看到。程序运行稳定需要更新它们吗？

**Comment by lightyears1998** [comment]
不是必须更新。不过更新依赖之后可以自动从Nuget源拉，换一台电脑也不需要手动下SQLite的SDK。

**Comment by MonreeStudio** [comment]
噢~原来是这样子，之前我一直是傻傻地手动下哈哈哈哈。OK！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: lightyears <notifications@github.com>
发送时间: Sunday, September 8, 2019 9:01:55 PM
收件人: MonreeStudio/MonreeDate-Update <MonreeDate-Update@noreply.github.com>
抄送: MonreeStudio <monreestudio@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [MonreeStudio/MonreeDate-Update] Nuget包可以更新啦 :happy (#1)


不是必须更新。不过更新依赖之后可以自动从Nuget源拉，换一台电脑也不需要手动下SQLite的SDK。

―
